{% set name = "seamm" %}
{% set version = "2025.10.22" %}
{% set sha256 = "45eeaae293712276324a34f60d4399e50211e6a2884d397fb19c0e5d9c1f77a4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/seamm-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 1
  noarch: python
  entry_points:
    - seamm=seamm.__main__:flowchart
    - run_flowchart=seamm.run_flowchart:run
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - bibtexparser
    - fasteners
    - humanize
    - jinja2
    - molsystem
    - numpy
    - packaging
    - pandas
    - pillow
    - pmw
    - py-cpuinfo
    - pyperclip
    - python >={{ python_min }}
    - python-dateutil
    - pyuca
    - reference-handler
    - seamm-dashboard-client
    - seamm-datastore
    - seamm-ff-util
    - seamm-util
    - seamm-widgets
    - stevedore

test:
  imports:
    - seamm
  commands:
    - pip check
    - seamm --help
  requires:
    - pip
    - freetype-py < 2.4.0
    - python {{ python_min }}

about:
  home: https://github.com/molssi-seamm/seamm
  summary: The Simulation Environment for Atomistic and Molecular Modeling (SEAMM)
  license: LGPL-3.0-or-later
  license_file: LICENSE
  doc_url: https://molssi-seamm.github.io/

extra:
  recipe-maintainers:
    - paulsaxe
