{% set name = "seamm" %}
{% set version = "2022.2.1" %}
{% set sha256 = "5fe3307ca97b00d0e5627378d7a7929c64b3697a2dec955507b2fed89af8fcd8" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/s/seamm/seamm-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  entry_points:
    - seamm=seamm.__main__:flowchart
    - run_flowchart=seamm.run_flowchart:run
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.8
    - setuptools
  run:
    - bibtexparser
    - fasteners
    - humanize
    - jinja2
    - molsystem
    - numpy
    - packaging
    - pandas
    - pillow
    - pmw
    - py-cpuinfo
    - python >=3.8
    - python-dateutil
    - pyuca
    - reference-handler
    - requests
    - requests-toolbelt
    - seamm-datastore
    - seamm-ff-util
    - seamm-util
    - seamm-widgets
    - stevedore

test:
  imports:
    - seamm
  commands:
    - pip check
    - seamm --help
    - run_flowchart --help
  requires:
    - pip

about:
  home: https://github.com/molssi-seamm/seamm
  summary: The Simulation Environment for Atomistic and Molecular Modeling (SEAMM)
  license: LGPL-3.0-or-later
  license_file: LICENSE
  doc_url: https://molssi-seamm.github.io/

extra:
  recipe-maintainers:
    - paulsaxe
